version: '3.8'

services:
  nginx:
    build: .
    container_name: mynginx
    ports:
      - "8080:8080"
    volumes:
      - ./html:/var/www/html
      - ./config/nginx.conf:/etc/nginx/http.d/default.conf
    restart: unless-stopped
