services:
  system:
    image: system
    build:
      context: .
      dockerfile: system.Dockerfile

  builder:
    image: build
    user: "${UID}:${GID}"
    build:
      context: .
      dockerfile: build.Dockerfile
    depends_on:
      - system

  runner:
    image: run-image
    user: "${UID}:${GID}"
    build:
      context: .
      dockerfile: run.Dockerfile
    depends_on:
      - builder