services:
  builder:
    image: builder_image
    build:
      context: .
      dockerfile: build.Dockerfile

  runner:
    build:
      context: .
      dockerfile: run.Dockerfile
    depends_on:
      - builder